export { createAIProvider } from './provider';
export { createOpenAIAdapter } from './providers/openai';
export { createAnthropicAdapter } from './providers/anthropic';
export { executeRewrite, createRewriteSession } from './rewrite';
export type { RewriteSession } from './rewrite';
export { computeDiff, hasMeaningfulDiff, getDiffStats } from './diff';
export { getSurroundingContext, getSelectedText, getHeadingStructure } from './context';
export { buildRewritePrompt, buildRestructurePrompt, buildTitleSuggestionPrompt, buildMetaSuggestionPrompt } from './prompts';
export { createStreamController, accumulateStream } from './stream';
export type { StreamController } from './stream';
